import { Oswald, Poiret_One } from "next/font/google";
import "./styles/tailwind.css";
import "./styles/globals.scss";

const oswald = Oswald({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700"],
    variable: "--font-oswald"
});

const poiret = Poiret_One({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-poiret"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${poiret.variable} font-oswald`}>
        {children}
      </body>
    </html>
  );
}
